// Azure Container Registry.
//
// Required by azd to push the control-plane and orchestrator images, and by AKS to pull them.
// This was missing from the first infrastructure pass — a genuine gap, caught when `azd provision`
// refused to run.
//
// Admin user is disabled. That is the whole point: an ACR admin account is a username/password pair,
// which is exactly the long-lived credential the secretless-identity rule prohibits. AKS pulls via an AcrPull role
// assignment on its *kubelet* identity — granted in aks.bicep, not here, because that identity is
// auto-generated by the managedClusters resource and doesn't exist until the cluster does. (An
// earlier revision granted this to the cluster's control-plane identity instead, which looks
// similar but is the wrong principal: nodes pull images using the kubelet identity, and the
// control-plane identity's own AcrPull grant did nothing — caught via a live 401 Unauthorized on
// `azd deploy`, not by any offline check.) azd itself pushes via the developer's own Entra identity.
//
// API version 2025-11-01: the newest stable (non-preview) version as of 2026-09-12
// (`az provider show --namespace Microsoft.ContainerRegistry`), needed for
// `networkRuleBypassAllowedForTasks` below - not present at 2023-07-01.

@description('Azure region.')
param location string

// minLength declared so Bicep can prove the composed registry name meets ACR's 5-character floor.
// uniqueString() always returns 13 characters, but that is not something the compiler knows.
@description('Deterministic suffix.')
@minLength(13)
param resourceToken string

@description('Tags applied to every resource.')
param tags object

@description('Registry SKU. Basic is sufficient for a development environment; Premium is required for private endpoints, geo-replication, and the IP firewall below.')
@allowed([
  'Basic'
  'Standard'
  'Premium'
])
param sku string = 'Basic'

// IP firewall (`networkRuleSet`), not Network Security Perimeter: verified against Microsoft
// Learn 2026-09-12, ACR has no NSP resource-association support at all, GA or preview (unlike
// Key Vault/Storage/Cosmos/Foundry/Speech — see network-security-perimeter.bicep). This is the
// only network control available to a registry short of a full Private Link + AKS VNet migration,
// and it requires Premium — Basic/Standard silently ignore `networkRuleSet`.
@description('Restrict the registry to allowedIpRanges instead of the open internet default. Requires sku to be Premium.')
param restrictPublicAccess bool = false

@description('IP address/CIDR ranges allowed through the firewall when restrictPublicAccess is true. Ignored otherwise.')
param allowedIpRanges array = []

// For-expressions can only be the direct value of a resource/module/variable/output declaration
// (BCP138), not nested inside a conditional expression - hence the separate variable rather than
// building this array inline inside the networkRuleSet ternary below.
var ipAllowRules = [
  for ip in allowedIpRanges: {
    action: 'Allow'
    value: ip
  }
]

resource registry 'Microsoft.ContainerRegistry/registries@2025-11-01' = {
  name: 'crgw${resourceToken}'
  location: location
  tags: tags
  sku: {
    name: sku
  }
  properties: {
    // No admin account. See the module header — this is a secretless-identity requirement, not a preference.
    adminUserEnabled: false
    publicNetworkAccess: 'Enabled'
    networkRuleSet: restrictPublicAccess
      ? {
          defaultAction: 'Deny'
          ipRules: ipAllowRules
        }
      : null
    // Verified live 2026-09-12: `azd deploy`'s remote build (ACR Tasks, azure.yaml's
    // `remoteBuild: true`) is itself subject to the same firewall and gets denied with
    // `restrictPublicAccess` on - the build agent's IP is neither the operator's own nor AKS's
    // outbound IP. Tasks stopped being an implicit trusted service from 2025-06-01; this opts
    // back in explicitly for tasks running as the registry's own system-assigned identity, the
    // same "AzureServices" bypass shape keyvault.bicep already uses, rather than trying to
    // allowlist ACR Tasks' own build-agent IP range (real, but a moving target requiring upkeep).
    networkRuleBypassAllowedForTasks: restrictPublicAccess
    policies: {
      // Untagged manifests accumulate and become an unreviewed supply-chain surface. Retention is
      // a Premium feature, so it is conditional rather than assumed.
      retentionPolicy: sku == 'Premium'
        ? {
            status: 'enabled'
            days: 30
          }
        : null
    }
  }
}

output loginServer string = registry.properties.loginServer
output registryName string = registry.name
