// Azure Container Registry.
//
// Required by azd to push the control-plane and orchestrator images, and by AKS to pull them.
// This was missing from the first infrastructure pass — a genuine gap, caught when `azd provision`
// refused to run.
//
// Admin user is disabled. That is the whole point: an ACR admin account is a username/password pair,
// which is exactly the long-lived credential the secretless-identity rule prohibits. AKS pulls via an AcrPull role
// assignment on its *kubelet* identity — granted in aks.bicep, not here, because that identity is
// auto-generated by the managedClusters resource and doesn't exist until the cluster does. (An
// earlier revision granted this to the cluster's control-plane identity instead, which looks
// similar but is the wrong principal: nodes pull images using the kubelet identity, and the
// control-plane identity's own AcrPull grant did nothing — caught via a live 401 Unauthorized on
// `azd deploy`, not by any offline check.) azd itself pushes via the developer's own Entra identity.
//
// API version 2023-07-01 is the newest the Bicep CLI can type-check.

@description('Azure region.')
param location string

// minLength declared so Bicep can prove the composed registry name meets ACR's 5-character floor.
// uniqueString() always returns 13 characters, but that is not something the compiler knows.
@description('Deterministic suffix.')
@minLength(13)
param resourceToken string

@description('Tags applied to every resource.')
param tags object

@description('Registry SKU. Basic is sufficient for a development environment; Premium is required for private endpoints and geo-replication.')
@allowed([
  'Basic'
  'Standard'
  'Premium'
])
param sku string = 'Basic'

resource registry 'Microsoft.ContainerRegistry/registries@2023-07-01' = {
  name: 'crgw${resourceToken}'
  location: location
  tags: tags
  sku: {
    name: sku
  }
  properties: {
    // No admin account. See the module header — this is a secretless-identity requirement, not a preference.
    adminUserEnabled: false
    publicNetworkAccess: 'Enabled'
    policies: {
      // Untagged manifests accumulate and become an unreviewed supply-chain surface. Retention is
      // a Premium feature, so it is conditional rather than assumed.
      retentionPolicy: sku == 'Premium'
        ? {
            status: 'enabled'
            days: 30
          }
        : null
    }
  }
}

output loginServer string = registry.properties.loginServer
output registryName string = registry.name
