"""T076a — pipeline creation and Azure DevOps "Workload identity federation" service-connection
configuration for the platform repository ``devops_project.py`` (T076) already pushes.

**Not a Sequencer-visible stage.** ``blueprint.yaml`` declares exactly one Azure-DevOps-related
stage (``devops_project``) and exactly one matching ``requiredPermissions`` entry (``Project
Administrator``, scoped to ``devops_project``) — confirmed before this module was written, not
re-derived here. This module is a plain helper invoked from ``DevOpsProjectStage.execute()``, never
registered with the ``Sequencer``.

Two independent pieces, verified against different sources because Microsoft Learn's own REST docs
(api-version 7.1, ``learn.microsoft.com/rest/api/azure/devops`` — the same host
``devops_project.py`` already established as reliable for this surface) render every polymorphic
request body as its *abstract* base shape only, never the concrete subtype fields a real caller
must send. That gap was independently true for both pieces below, so each is cross-checked against
a second, concrete source rather than Learn's docs alone.

**1. Pipeline creation — verified 2026-08-01.**

- ``POST {organization}/{project}/_apis/pipelines?api-version=7.1`` creates a pipeline; ``GET`` the
  same path lists them. Neither has a name-filter query parameter — found by listing and matching
  client-side, the same pattern ``devops_project.py`` already uses for projects and repositories.
- Learn's own "Pipelines - Create" page documents ``CreatePipelineConfigurationParameters`` as only
  ``{type: ConfigurationType}``. ``ConfigurationType`` does include the ``yaml`` enum value this
  module needs, but the concrete ``path``/``repository`` fields a real YAML-backed pipeline requires
  are entirely absent from the page — an autogenerated-docs limitation (the same polymorphic-body
  problem, not a real API gap). Cross-checked against two independent, mutually consistent worked
  examples (rasmustherkelsen.wordpress.com and johnnyreilly.com, both documenting the same
  Microsoft-undocumented gap independently): ``{"folder": ..., "name": ..., "configuration":
  {"type": "yaml", "path": ..., "repository": {"id": ..., "name": ..., "type": "azureReposGit"}}}``.
  This module points ``path`` at ``/azure-pipelines.yml`` — the file this same change adds to
  ``infra/blueprints/standard-production-fabric/``, so ``devops_project.py``'s own repository push
  carries it before this ever runs.

**2. Service-connection creation ("Workload identity federation", Manual mode) — verified
2026-08-01, and see the blocker below before assuming this is wired in anywhere.**

- ``POST {organization}/_apis/serviceendpoint/endpoints?api-version=7.1`` creates a service
  connection (organisation-scoped; project membership is set via
  ``serviceEndpointProjectReferences`` in the body, not a path segment). ``GET
  {organization}/{project}/_apis/serviceendpoint/endpoints?api-version=7.1`` lists them
  project-scoped (again no name filter; matched client-side). ``PUT
  {organization}/_apis/serviceendpoint/endpoints/{endpointId}?api-version=7.1`` updates one.
- Learn's own "Endpoints - Create" worked example uses the classic secret-based ``"scheme":
  "ServicePrincipal"`` shape, never ``WorkloadIdentityFederation`` — Microsoft has not published a
  worked REST example for this specific scheme. Verified instead against
  ``microsoft/terraform-provider-azuredevops``'s own ``resource_serviceendpoint_azurerm.go``
  (``expandServiceEndpointAzureRM``) — the Terraform provider the Azure DevOps blog post
  ``identity.py`` already cites recommends for exactly this connection type, and which necessarily
  constructs the same REST body this module must, since it calls the same REST API with no SDK in
  between. Confirmed fields for ``WorkloadIdentityFederation`` in **Manual** creation mode (i.e. the
  caller already has a real managed identity — never Azure DevOps's own auto-provisioned one;
  **Automatic** mode is for that latter case and does not apply here):
  ``authorization.scheme = "WorkloadIdentityFederation"``, ``authorization.parameters =
  {"serviceprincipalid": <client id>, "tenantid": <tenant id>}`` — the Go source's own error path
  (``"serviceprincipalid is required for WorkloadIdentityFederation"``) confirms this is a hard
  requirement, not optional — and ``data = {"creationMode": "Manual", "environment": "AzureCloud",
  "scopeLevel": "Subscription", "subscriptionId": <id>, "subscriptionName": <label>}``.
  ``subscriptionName`` is a required field with no corresponding value anywhere in this platform's
  data model (``DeploymentPlan``/``Deployment`` carry a subscription *id*, never a display name —
  the same kind of gap ``fabric.py`` hit for ``capacity_admin_upn``); nothing found in this
  research shows Azure DevOps validating this string against the live subscription in Manual mode
  (only Automatic mode's interactive OAuth flow populates it from a real subscription list), so this
  module uses the subscription id itself as the label — cosmetic only, never used for authorization,
  which is governed entirely by ``scopeLevel``/``subscriptionId``/``tenantid``/
  ``authorization.parameters`` above.
- The Entra **client id** ``serviceprincipalid`` needs is the platform's managed identity's own
  Application (client) ID. Not resolved via a new ``azure-mgmt-msi`` dependency (not currently a
  project dependency, and not installed — confirmed by import failure locally). ``main.bicep``
  already exposes it directly: ``output managedIdentityClientId string =
  identity.outputs.clientId``. Azure Deployment Stacks' own ``GET`` response mirrors the underlying
  ARM deployment's ``outputs`` verbatim (confirmed against the same versioned OpenAPI source
  ``infrastructure.py``'s docstring already verified,
  ``Microsoft.Resources/deploymentStacks/stable/2025-07-01/deploymentStacks.json``
  — ``DeploymentStackProperties.outputs``: "The outputs of the deployment resource created by the
  deployment stack"). ``resolve_managed_identity_client_id`` below reads the same deployment stack
  ``infrastructure.py`` (T077) and ``networking.py`` (T079) already read, via the same
  ``deployment_stack_name``/``ARM_ENDPOINT``/``ARM_SCOPE`` helpers, and pulls
  ``properties.outputs.managedIdentityClientId.value`` — no new Azure SDK dependency, and no new
  permission surface (a ``GET`` on a resource the ``infrastructure`` stage's own ``Contributor``
  grant already covers).

**A real, unresolved sequencing blocker — flagged, not solved here.** The managed identity's client
id above only exists once the ``infrastructure`` stage's deployment stack has actually applied — and
``blueprint.yaml``'s own stage graph makes ``infrastructure`` ``dependsOn: [devops_project]``, i.e.
**``devops_project`` (T076, this module's caller) runs strictly before the managed identity is ever
created.** ``Sequencer.run`` (T070, ``engine/sequencer.py``) walks ``execution_order()`` once, front
to back, and its own resume logic (``skipping``/``resume_after`` against
``deployment.checkpoint.stage_name``) explicitly skips past any stage at or before the last
completed checkpoint on retry — so ``devops_project`` is never re-entered once it reaches
``SUCCEEDED``, even if a later stage (``fabric``, ``monitoring``, …) fails and the deployment is
retried. There is no point in this platform's current execution model at which ``devops_project``
could correctly create a **Manual**-mode ``WorkloadIdentityFederation`` service connection, because
that creation call requires a real, already-existing client id as an explicit, validated request
parameter, and no client id exists yet at that point in the DAG. (``identity.py``'s own docstring
forward-references this module — "T076a later creates the Azure DevOps-side service connection" —
without having noticed this ordering conflict either; ``identity.py`` (T080) itself only runs after
``infrastructure``, later still than ``devops_project``.)

This is not a data problem this module can route around — there is no deterministic way to predict
an Entra client id before Azure assigns one — and papering over it (reporting ``SUCCEEDED`` from
``devops_project`` without actually creating the service connection, or creating one with an empty
or placeholder client id) is exactly the "silent fallback on the production path" this codebase
forbids. ``ensure_service_connection`` and ``resolve_managed_identity_client_id`` below
are implemented completely and independently unit-tested, and are **called from the ``identity``
stage (T080), not from here** — resolved 2026-08-01, the same call this docstring already
identified as the most plausible fix: ``identity`` already runs after ``infrastructure`` (so the
client id exists) and already resolves the Azure DevOps organisation GUID this same connection's
issuer needs. See ``identity.py``'s own module docstring for the wiring. Only ``ensure_pipeline`` is
called from ``devops_project.py`` itself, since pipeline creation has no such dependency (it only
needs the already-pushed repository).
"""

from __future__ import annotations

from typing import Any

import httpx

API_VERSION = "7.1"
PIPELINE_PERMISSIONS_API_VERSION = "7.2-preview.1"
SERVICE_CONNECTION_TYPE = "azurerm"
SERVICE_CONNECTION_SCHEME = "WorkloadIdentityFederation"
SERVICE_CONNECTION_URL = "https://management.azure.com/"
YAML_PIPELINE_PATH = "/azure-pipelines.yml"
ROLLBACK_YAML_PIPELINE_PATH = "/rollback.yml"


class DevOpsPipelinesConfigurationError(Exception):
    """A domain-level failure this module recognised by name — not an HTTP error, not a bug here."""


def pipeline_name(project_name: str) -> str:
    """Deterministic pipeline name, derived from the project name ``devops_project.py`` already
    computed and passes in — no independent naming scheme, the same reasoning ``identity.py`` gives
    for reusing ``deployment_project_name`` rather than inventing a second convention."""
    return f"{project_name}-platform-release"


def rollback_pipeline_name(project_name: str) -> str:
    """Deterministic rollback pipeline name for the same project."""
    return f"{project_name}-rollback-pipeline"


class DevOpsPipelinesConfigurer:
    """Helper invoked from both ``DevOpsProjectStage`` (``ensure_pipeline``) and ``IdentityStage``
    (``ensure_service_connection``/``resolve_managed_identity_client_id``) — not a ``Stage`` itself.
    See this module's docstring for why the service-connection half is called from ``identity.py``
    rather than from here.
    """

    def __init__(self, *, http_client: httpx.AsyncClient) -> None:
        self._client = http_client

    # ------------------------------------------------------------------
    # Pipeline — wired into devops_project.py's execute().
    # ------------------------------------------------------------------

    async def ensure_pipeline(
        self,
        *,
        organization_url: str,
        project_name: str,
        repository_id: str,
        repository_name: str,
        headers: dict[str, str],
        pipeline_name_override: str | None = None,
        yaml_path: str = YAML_PIPELINE_PATH,
    ) -> tuple[bool, str, str]:
        """Idempotent create-if-absent. Returns ``(applied, name, pipeline_id)`` — the id is what
        protected-resource authorization grants are keyed on."""
        name = pipeline_name_override or pipeline_name(project_name)
        existing = await self._find_pipeline(organization_url, project_name, name, headers)
        if existing is not None:
            return False, name, str(existing["id"])

        url = f"{organization_url}/{project_name}/_apis/pipelines?api-version={API_VERSION}"
        body = {
            "name": name,
            "folder": "\\",
            "configuration": {
                "type": "yaml",
                "path": yaml_path,
                "repository": {
                    "id": repository_id,
                    "name": repository_name,
                    "type": "azureReposGit",
                },
            },
        }
        response = await self._client.post(url, headers=headers, json=body)
        response.raise_for_status()
        created = response.json()
        return True, name, str(created["id"])

    async def _find_pipeline(
        self, organization_url: str, project_name: str, name: str, headers: dict[str, str]
    ) -> dict[str, Any] | None:
        url = f"{organization_url}/{project_name}/_apis/pipelines?api-version={API_VERSION}"
        response = await self._client.get(url, headers=headers)
        response.raise_for_status()
        for pipeline in response.json()["value"]:
            if pipeline["name"] == name:
                result: dict[str, Any] = pipeline
                return result
        return None

    # ------------------------------------------------------------------
    # Service connection — invoked from devops_project.py's execute() (FR-006a's bootstrap
    # identity makes the managed identity's client id available up front, so the sequencing
    # blocker that once required this to wait for the `identity` stage no longer applies).
    # ------------------------------------------------------------------

    async def ensure_service_connection(
        self,
        *,
        organization_url: str,
        project_id: str,
        project_name: str,
        connection_name: str,
        subscription_id: str,
        tenant_id: str,
        managed_identity_client_id: str,
        headers: dict[str, str],
    ) -> tuple[bool, str, dict[str, Any] | None]:
        """Returns ``(applied, connection_id, endpoint_document)``. The document carries the
        effective workloadIdentityFederation issuer/subject ADO generated server-side — values
        no caller can predict before creation, and exactly what the matching federated
        credential must trust."""
        existing = await self._find_service_connection(
            organization_url, project_name, connection_name, headers
        )
        body = self._service_connection_body(
            project_id=project_id,
            project_name=project_name,
            connection_name=connection_name,
            subscription_id=subscription_id,
            tenant_id=tenant_id,
            managed_identity_client_id=managed_identity_client_id,
        )

        if existing is not None:
            if self._service_connection_matches(existing, body):
                return False, str(existing["id"]), existing
            url = (
                f"{organization_url}/_apis/serviceendpoint/endpoints/{existing['id']}"
                f"?api-version={API_VERSION}"
            )
            response = await self._client.put(url, headers=headers, json=body)
            response.raise_for_status()
            updated: dict[str, Any] = response.json() if response.content else existing
            return True, str(existing["id"]), updated

        url = f"{organization_url}/_apis/serviceendpoint/endpoints?api-version={API_VERSION}"
        response = await self._client.post(url, headers=headers, json=body)
        response.raise_for_status()
        created: dict[str, Any] = response.json()
        return True, str(created["id"]), created

    async def _find_service_connection(
        self, organization_url: str, project_name: str, name: str, headers: dict[str, str]
    ) -> dict[str, Any] | None:
        url = (
            f"{organization_url}/{project_name}/_apis/serviceendpoint/endpoints"
            f"?api-version={API_VERSION}"
        )
        response = await self._client.get(url, headers=headers)
        response.raise_for_status()
        for endpoint in response.json()["value"]:
            if endpoint["name"] == name:
                result: dict[str, Any] = endpoint
                return result
        return None

    async def get_service_connection(
        self,
        *,
        organization_url: str,
        project_name: str,
        connection_name: str,
        headers: dict[str, str],
    ) -> dict[str, Any] | None:
        """Read the current service-connection document by name."""
        return await self._find_service_connection(
            organization_url, project_name, connection_name, headers
        )

    @staticmethod
    def federation_parameters(endpoint: dict[str, Any]) -> tuple[str, str] | None:
        """The ``(issuer, subject)`` this service connection will present, or ``None`` when the
        endpoint document carries none.

        Since sprint 253 new WorkloadIdentityFederation connections default to the Microsoft
        Entra issuer flavour (``https://login.microsoftonline.com/{tenant}/v2.0`` +
        ``/eid1/c/pub/t/…/a/…/sc/{orgGuid}/{endpointGuid}``), whose subject embeds the
        server-assigned endpoint id — uncomputable before creation. The legacy Azure DevOps
        issuer flavour (``https://vstoken.dev.azure.com/{orgGuid}`` + ``sc://{org}/{project}/
        {connection}``) is what ``identity.py``'s bootstrap-time credential predicts; it is
        deprecated (retirement announced for 2027) but still minted for some configurations.
        Whichever flavour ADO chose is authoritative here, which is why callers must read these
        values back rather than assume either format.
        """
        params = (endpoint.get("authorization") or {}).get("parameters") or {}
        issuer = params.get("workloadIdentityFederationIssuer")
        subject = params.get("workloadIdentityFederationSubject")
        if issuer and subject:
            return str(issuer), str(subject)
        return None

    @staticmethod
    def _service_connection_body(
        *,
        project_id: str,
        project_name: str,
        connection_name: str,
        subscription_id: str,
        tenant_id: str,
        managed_identity_client_id: str,
    ) -> dict[str, Any]:
        description = (
            "Groundwork-managed workload identity federation connection to the deployment "
            "target subscription."
        )
        return {
            "name": connection_name,
            "type": SERVICE_CONNECTION_TYPE,
            "url": SERVICE_CONNECTION_URL,
            "description": description,
            "authorization": {
                "scheme": SERVICE_CONNECTION_SCHEME,
                "parameters": {
                    "serviceprincipalid": managed_identity_client_id,
                    "tenantid": tenant_id,
                },
            },
            "data": {
                "creationMode": "Manual",
                "environment": "AzureCloud",
                "scopeLevel": "Subscription",
                "subscriptionId": subscription_id,
                "subscriptionName": subscription_id,
            },
            "isShared": False,
            "isReady": True,
            "serviceEndpointProjectReferences": [
                {
                    "name": connection_name,
                    "description": description,
                    "projectReference": {"id": project_id, "name": project_name},
                }
            ],
        }

    @staticmethod
    def _service_connection_matches(existing: dict[str, Any], expected: dict[str, Any]) -> bool:
        auth = existing.get("authorization") or {}
        params = auth.get("parameters") or {}
        data = existing.get("data") or {}
        expected_auth = expected["authorization"]
        expected_params = expected_auth["parameters"]
        expected_data = expected["data"]
        return (
            auth.get("scheme") == expected_auth["scheme"]
            and params.get("serviceprincipalid") == expected_params["serviceprincipalid"]
            and params.get("tenantid") == expected_params["tenantid"]
            and data.get("scopeLevel") == expected_data["scopeLevel"]
            and data.get("subscriptionId") == expected_data["subscriptionId"]
        )

    # resolve_managed_identity_client_id() removed 2026-08-24 (Clarifications, FR-006a) — it read
    # the client id from the infrastructure stage's own deployment stack outputs, which no longer
    # exists under the trigger-and-poll model (System's credential cannot read that stack either,
    # per FR-006's bootstrap-only scope). The client id now comes directly from
    # ``SubscriptionEntitlement.bootstrap_identity_client_id`` (``api/tenants.py``'s
    # ``bootstrap_identity`` route), available before this deployment even starts.
